#!/bin/bash

#Finds Firefox and focuses
xdotool search --onlyvisible --class "firefox" windowactivate --sync   

#Entry point, quits fullscreen
xdotool key Escape

#tabs out of the player
xdotool key --repeat 12 --delay 100 Tab

#Siteinternal forward shortcut
xdotool key --delay 50 ctrl+Right
sleep 5

#logs the episode
#Custom script
$HOME/EasyOnePace/LogEpisodeOnePace

#tabs through all the wierd stuff on site to bypass popup
xdotool key --repeat 16 --delay 100 Tab

#start the episode and skip Intro
xdotool key Return
sleep 2
xdotool key f
sleep 1
xdotool key --repeat 30 --delay 100 Right
xdotool mousemove 9000 0
